version: '2.3'

services:
  conductor-server:
    environment:
      - CONFIG_PROP=config-mysql.properties
    image: harbor.nexr.kr/denver/conductor-server-mariadb:test
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    networks:
      - internal
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl","-I" ,"-XGET", "http://localhost:8080/health"]
      interval: 60s
      timeout: 30s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"


volumes:
  esdata-conductor:
    driver: local

networks:
  internal:
